// ...existing code...
// Add this route for contractors to get their assigned campaigns
router.get('/contractor', authenticateToken, campaignController.getContractorCampaigns);
// ...existing code...